repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: Automatically remove trailing whitespace from files.

      - id: end-of-file-fixer
        name: Ensure files end with a newline
        description: Ensure that files end with a newline.
